stages:
    - prepare
    - build
    - deploy

init:
    stage: prepare
    retry: 2
    tags:
        - unreal
        - windows
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^update binaries to.*/
            - $CI_COMMIT_MESSAGE =~ /^CI-SKIP*/
    script:
        - git-lfs install
        - git-lfs pull

build project:
    stage: build
    cache:
        paths:
            - Intermediate/Build
            - Binaries
    tags:
        - windows
        - unreal
        - whenever
    only:
        refs:
            - dev
            - merge_requests
        changes:
            - Source/**
            - Scripts/**
            - .gitlab-ci.yml
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^update binaries to.*/
            - $CI_COMMIT_MESSAGE =~ /^CI-SKIP*/
    script:
        - .\ue4versionator.exe -user-config .ue4v-gitlab-user
        - git submodule init
        - .\Scripts\PrepareBinaries.bat
        - .\Scripts\CompileBinaries.bat
        - .\Scripts\CompileGameBinaries.bat

package project:
    stage: build
    retry: 2
    cache:
        paths:
            - Saved
            - Intermediate
            - AutoBuild
            - Binaries
    tags:
        - windows
        - unreal
    only:
        - schedules
    script:
        - .\ue4versionator.exe -user-config .ue4v-gitlab-user
        - git submodule init
        - .\Scripts\PrepareBinaries.bat
        - .\Scripts\CompileBinaries.bat
        - .\Scripts\CompileGameBinaries.bat
        - .\Scripts\BuildFiles.bat

update branches:
    stage: deploy
    tags:
        - windows
    only:
        refs:
            - schedules
    script: .\Scripts\UpdateBranch.bat

deploy binaries:
    stage: deploy
    tags:
        - windows
        - unreal
        - whenever
    only:
        changes:
            - Config/DefaultGame.ini
            - Scripts/**
            - Plugins/**/*.uplugin
            - ./ProjectBorealis.uproject
    except:
        refs:
            - schedules
    script:
        - .\Scripts\PushBinaries.bat
        
deploy nightly:
    stage: deploy
    tags:
        - windows
        - unreal
    cache:
        paths:
            - Saved
            - Intermediate
            - AutoBuild
    only:
        refs:
            - schedules
        variables:
            - $CI_COMMIT_REF_NAME == "dev"
    script: 
        - .\Scripts\Archive.bat
        - RD Intermediate\Staging /S /Q
        - RD Saved\StagedBuilds /S /Q
        - RD Saved\Temp /S /Q
        - RD Saved\TmpPackaging /S /Q
        - RD Saved\Logs /S /Q
        - RD AutoBuild /S /Q
    artifacts:
        name: "Project Borealis-%CI_COMMIT_REF_NAME%-build"
        expire_in: 1 day
        paths:
            - AutoBuild_Archive\project_borealis.exe

deploy changelist:
    stage: deploy
    tags:
        - windows
        - unreal
    cache:
        paths:
            - Saved
            - Intermediate
            - AutoBuild
    only:
        refs:
            - schedules
        variables:
            - $CI_COMMIT_REF_NAME == "master"
    script: 
        - .\Scripts\Archive.bat
        - RD Intermediate\Staging /S /Q
        - RD Saved\StagedBuilds /S /Q
        - RD Saved\Temp /S /Q
        - RD Saved\TmpPackaging /S /Q
        - RD Saved\Logs /S /Q
        - RD AutoBuild /S /Q
    artifacts:
        name: "Project Borealis-%CI_COMMIT_REF_NAME%-build"
        expire_in: 1 week
        paths:
            - AutoBuild_Archive\project_borealis.exe
            
deploy snapshot:
    stage: deploy
    tags:
        - windows
        - unreal
    cache:
        paths:
            - Saved
            - Intermediate
            - AutoBuild
    only:
        refs:
            - schedules
        variables:
            - $CI_COMMIT_REF_NAME == "stable"
    script: 
        - .\Scripts\Archive.bat
        - RD Intermediate\Staging /S /Q
        - RD Saved\StagedBuilds /S /Q
        - RD Saved\Temp /S /Q
        - RD Saved\TmpPackaging /S /Q
        - RD Saved\Logs /S /Q
        - RD AutoBuild /S /Q
    artifacts:
        name: "Project Borealis-%CI_COMMIT_REF_NAME%-build"
        expire_in: 2 weeks
        paths:
            - AutoBuild_Archive\project_borealis.exe

deploy release:
    stage: deploy
    tags:
        - windows
        - unreal
    cache:
        paths:
            - Saved
            - Intermediate
            - AutoBuild
    only:
        refs:
            - schedules
            - $CI_COMMIT_REF_NAME == "release"
        variables:
    script: 
        - .\Scripts\Archive.bat
        - RD Intermediate\Staging /S /Q
        - RD Saved\StagedBuilds /S /Q
        - RD Saved\Temp /S /Q
        - RD Saved\TmpPackaging /S /Q
        - RD Saved\Logs /S /Q
        - RD AutoBuild /S /Q
    artifacts:
        name: "Project Borealis-%CI_COMMIT_REF_NAME%-build"
        expire_in: 1 month
        paths:
            - AutoBuild_Archive\project_borealis.exe