name: promoted -> master

on:
  push:
    branches: [ promoted ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge promoted -> master
      uses: everlytic/branch-merge@master
      with:
        target_branch: master
        github_token: ${{ secrets.REPO_TOKEN }}
